title: Psion Software Index
author: Jason Morley
email: support@jbmorley.co.uk
description: "Index of software for the Psion range of palmtop computers."
baseurl: ""
url: "https://software.psion.community"

plugins:
  - jekyll-typogrify
  - jekyll-gfm-admonitions
destination: ../_site

defaults:
  - values:
      layout: "default"
